# MTD
diamonds: 
  dataset: "diamonds"
  model: codegen-350M-mono-measurement_pred-diamonds
  epochs: 5 
  frac_warmup_steps: 0.1
  max_length: 1024
  feature_dim: 1024
generated_stories: 
  dataset: "generated_stories"
  model: pythia-1_4b-deduped-measurement_pred-generated_stories
  epochs: 4
  frac_warmup_steps: 0.15
  max_length: 1536
  feature_dim: 2048