TopK_0.1: 
  diamonds: 
    lr: 2e-5 
    aux_weight: 1.0 
  generated_stories: 
    lr: 3e-6
    aux_weight: 2.5
DivDis: 
  diamonds: 
    lr: 2e-5 
    aux_weight: 3.0
  generated_stories: 
    lr: 3e-6
    aux_weight: 3.0
FT_Trusted: 
  diamonds: 
    lr: 2e-5 
  generated_stories: 
    lr: 5e-3
Probe_for_Evidence_of_Tamper: 
  diamonds: 
    lr: 2e-4
  generated_stories: 
    lr: 5e-4
