DivDis: 
  loss_type: DIVDIS 
TopK_0.1: 
  loss_type: TOPK
  mix_rate_lower_bound: 0.1
  mix_rate_schedule: linear
Probe_for_Evidence_of_Tamper: 
  loss_type: ERM 
  aux_weight: 0.0 
  heads: 1
  source_labels: 
  - sensors_agree
  split_source_target: False
  target_only_disagree: True
  freeze_model: True
FT_Trusted: 
  loss_type: ERM 
  aux_weight: 0.0 
  heads: 1
Measurement_Predictor: 
  loss_type: ERM 
  heads: 1 
  train: False 
  load_prior_probe: True
