seed: 0
dataset: diamonds-seed${seed}
model: codegen-350M-mono-measurement_pred-diamonds-seed${seed}
epochs: 5 
frac_warmup_steps: 0.1
max_length: 1024
feature_dim: 1024
bootstrap_eval: False
micro_batch_size: 4